# fly.toml app configuration file generated for bloom-bot on 2023-05-26T22:18:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bloom-bot"
primary_region = "bos"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[processes]
  discord = "python -u -m bot.app"
  web = "python -m streamlit run www/main.py"

[http_service]
  internal_port = 8501
  processes = ["web"]
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
